import Foundation
import Nexus

// MARK: - Authenticatable Protocol

/// Conform your user model to this protocol so the auth system can identify users.
///
/// ```swift
/// @Schema("users")
/// struct User: Authenticatable {
///     @ID var id: UUID
///     @Column var email: String
///     @Column var hashedPassword: String
///     // ...
///
///     var authID: String { id.uuidString }
/// }
/// ```
public protocol Authenticatable: Sendable {
    /// A string that uniquely identifies this user (typically `id.uuidString`).
    var authID: String { get }
}

// MARK: - Session Token Keys

/// Session key where the auth token is stored.
private let sessionTokenKey = "_roost_auth_token"

/// Session key where the user ID is stored for quick access.
private let sessionUserIDKey = "_roost_user_id"

// MARK: - Connection Extensions — Session Auth

extension Connection {

    // MARK: Login

    /// Authenticate a user and store their identity in the session.
    ///
    /// Call this after you've validated credentials (email + password) in
    /// your route handler. A random token is generated and stored in the
    /// session. Your app should also persist the hashed token (via
    /// ``Auth/sha256Hex(_:)``) in a `user_tokens` table for server-side
    /// validation.
    ///
    /// ```swift
    /// POST("/auth/login") { conn in
    ///     // ... verify password ...
    ///     let (conn, token) = conn.loginUser(user)
    ///     // Persist Auth.sha256Hex(token) to your user_tokens table
    ///     return conn.redirect(to: "/dashboard")
    /// }
    /// ```
    ///
    /// - Parameters:
    ///   - user: The authenticated user.
    ///   - remember: Reserved for application policy; does not change the session TTL.
    ///   - token: A token to store, generated by ``Auth/generateToken(bytes:)`` by default.
    /// - Returns: A tuple of the updated connection (with session data set)
    ///   and the plain-text token. Hash the token before storing in DB.
    public func loginUser<U: Authenticatable>(
        _ user: U,
        remember: Bool = false,
        token: String = Auth.generateToken()
    ) -> (Connection, String) {
        let conn = self
            .putSessionValue(sessionTokenKey, token)
            .putSessionValue(sessionUserIDKey, user.authID)
            .assign(key: AuthAssign.currentUser, value: user)
            .assign(key: AuthAssign.currentUserID, value: user.authID)
            .assign(key: AuthAssign.authContext, value: "session")
            .renewSessionID()

        return (conn, token)
    }

    // MARK: Logout

    /// Clear the current user's authentication from the session.
    ///
    /// Removes session-stored auth data. Your route handler should also
    /// delete the token record from the `user_tokens` table.
    ///
    /// ```swift
    /// DELETE("/auth/logout") { conn in
    ///     // Delete token from DB first, then:
    ///     return conn.logoutUser()
    ///         .redirect(to: "/")
    /// }
    /// ```
    public func logoutUser() -> Connection {
        var conn = self
            .deleteSessionValue(sessionTokenKey)
            .deleteSessionValue(sessionUserIDKey)
        conn.assigns.removeValue(forKey: AuthAssign.currentUser)
        conn.assigns.removeValue(forKey: AuthAssign.currentUserID)
        conn.assigns.removeValue(forKey: AuthAssign.authContext)
        conn.assigns.removeValue(forKey: AuthAssign.currentScope)
        return conn
    }

    // MARK: Current User

    /// The session-stored auth token (plain text).
    ///
    /// Returns `nil` when no user is logged in. Use this to look up the
    /// matching `UserToken` record in your database.
    public var authSessionToken: String? {
        sessionValue(sessionTokenKey) as? String
    }

    /// The session-stored user ID string.
    ///
    /// Populated by ``loginUser(_:remember:token:)``.
    public var authUserID: String? {
        sessionValue(sessionUserIDKey) as? String
    }

    /// Store a loaded user in assigns so downstream plugs / handlers can
    /// access it via ``currentUser(_:)``.
    ///
    /// Typically called inside a plug that loads the user from the database
    /// using the session token.
    ///
    /// ```swift
    /// // Inside your "fetch user" plug:
    /// if let user = try await loadUserFromDB(sessionToken) {
    ///     conn = conn.setCurrentUser(user)
    /// }
    /// ```
    public func setCurrentUser<U: Authenticatable>(_ user: U) -> Connection {
        self
            .assign(key: AuthAssign.currentUser, value: user)
            .assign(key: AuthAssign.currentUserID, value: user.authID)
    }

    /// Get the authenticated user from assigns, cast to the expected type.
    ///
    /// Returns `nil` if no user has been loaded or the type doesn't match.
    ///
    /// ```swift
    /// if let user = conn.currentUser(User.self) {
    ///     // user is authenticated
    /// }
    /// ```
    public func currentUser<U: Authenticatable>(_ type: U.Type) -> U? {
        assigns[AuthAssign.currentUser] as? U
    }

    /// `true` when a user has been stored in assigns (i.e. authenticated).
    public var isAuthenticated: Bool {
        assigns[AuthAssign.currentUserID] != nil
    }

    /// Identity established by authentication middleware for this request.
    /// Prefer this to the raw session hint (`authUserID`) when scoping queries.
    public var authenticatedUserID: String? {
        assigns[AuthAssign.currentUserID] as? String
    }
}
