// JobsPatterns.swift
// Design specification for Roost.Jobs — inspired by Elixir's Oban
//
// Backed by swift-jobs (hummingbird-project) with Valkey or Postgres drivers.
// Roost adds a thin DSL, a generator, and dev-mode introspection.
//
// Driver selection:
//   .valkey(client:)    — fast, ephemeral (acceptable job loss on crash)
//   .postgres(client:)  — durable, transactional, survives restarts (recommended)

// MARK: - 1. App-level configuration

struct DonutShopApp: RoostApp {
    var jobs: JobQueue {
        if Roost.env == .test {
            return JobQueue.inMemory()
        }
        return JobQueue.postgres(spectro: spectro)  // reuses the Spectro connection pool
    }

    var routes: [Route] { [] }
}

// MARK: - 2. Define a job

// Generated by: roost gen job WelcomeEmail

struct WelcomeEmailJob: RoostJob {
    struct Parameters: Codable {
        let userID: UUID
        let email:  String
    }

    // Retry strategy: exponential back-off, up to 3 attempts
    static var retryStrategy: RetryStrategy { .exponentialJitter(maxAttempts: 3) }

    // Optional per-job timeout
    static var timeout: Duration { .seconds(30) }

    func execute(parameters: Parameters, context: JobContext) async throws {
        // context.spectro — access to the database
        let user = try await context.spectro.find(User.self, id: parameters.userID)
        try await Mailer.send(
            to:      parameters.email,
            subject: "Welcome to Donut Shop!",
            body:    "Hi \(user.name), your account is ready."
        )
    }
}

// MARK: - 3. Enqueue from a route handler

func registerUser(_ conn: Connection) async throws -> Connection {
    let user = try conn.decode(User.self)
    try await conn.spectro.insert(user)

    // Enqueue runs the job in the background; this request returns immediately
    try await conn.jobs.push(WelcomeEmailJob.self, parameters: .init(
        userID: user.id,
        email:  user.email
    ))

    return conn.redirect(to: "/dashboard")
}

// MARK: - 4. Schedule a recurring job

// Configured once at app startup (cron-style or convenience helpers):
//
//   struct DonutShopApp: RoostApp {
//       var scheduledJobs: [ScheduledJob] {
//           schedule(DailyReportJob.self, parameters: .init(), cron: "0 8 * * 1-5") // weekdays at 8am
//           schedule(PurgeOldOrdersJob.self, parameters: .init(), every: .days(7))
//       }
//   }

// MARK: - 5. Job with database access

struct OrderConfirmationJob: RoostJob {
    struct Parameters: Codable {
        let orderID: UUID
    }

    func execute(parameters: Parameters, context: JobContext) async throws {
        guard let order = try await context.spectro.find(Order?.self, id: parameters.orderID) else {
            // Returning normally (without throwing) marks the job as discarded, not failed
            return
        }
        try await context.spectro.update(order, set: \.status, to: "confirmed")
        try await context.jobs.push(WelcomeEmailJob.self, parameters: .init(
            userID: order.userID,
            email:  order.userEmail
        ))
    }
}

// MARK: - 6. Middleware (metrics, tracing, custom logging)

// struct JobLoggingMiddleware: JobMiddleware {
//     func execute<J: RoostJob>(
//         job: J, parameters: J.Parameters, context: JobContext,
//         next: (J, J.Parameters, JobContext) async throws -> Void
//     ) async throws {
//         let start = ContinuousClock.now
//         do {
//             try await next(job, parameters, context)
//             logger.info("Job \(J.name) succeeded in \(ContinuousClock.now - start)")
//         } catch {
//             logger.error("Job \(J.name) failed: \(error)")
//             throw error
//         }
//     }
// }

// MARK: - 7. Testing jobs synchronously

// In test mode the in-memory driver runs jobs inline (no background workers):
//
//   let app = try await TestApp(DonutShopApp.self)
//   _ = try await app.post("/users", json: ["name": "Alice", "email": "alice@example.com"])
//
//   // Job was executed inline during the test
//   let sentEmails = app.mailer.sentEmails
//   #expect(sentEmails.count == 1)
//   #expect(sentEmails[0].to == "alice@example.com")
//
// To inspect the queue without executing:
//   let queued = app.jobs.pending(WelcomeEmailJob.self)
//   #expect(queued.count == 1)
